/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agencevoyage.view;

import agencevoyage.model.Journey;
import agencevoyage.model.JourneyManager;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author UTILISATEUR
 */
public class BookingScreen extends javax.swing.JPanel {
    
    private JPanel contentPane;
    private JFrame currentframe;
    private Journey journey;
    /**
     * Creates new form BookingScreen
     */
    public BookingScreen(JPanel panel, JFrame frame, Journey j) {
        contentPane = panel;
        currentframe = frame;
        journey = j;
        initComponents();
        country_lbl.setText(j.getCountry());
        city_lbl.setText(j.getCity());
        
        refreshComboBox();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        city_lbl = new javax.swing.JLabel();
        country_lbl = new javax.swing.JLabel();
        screen_title_lbl = new javax.swing.JLabel();
        nb_place_box = new javax.swing.JComboBox<>();
        nb_place_lbl = new javax.swing.JLabel();
        submit = new javax.swing.JButton();

        city_lbl.setText("city");

        country_lbl.setText("country");

        screen_title_lbl.setText("Réservation");

        nb_place_lbl.setText("Nombre de place : ");

        submit.setText("Valider");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submit)
                    .addComponent(screen_title_lbl)
                    .addComponent(city_lbl)
                    .addComponent(country_lbl)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nb_place_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nb_place_box, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(screen_title_lbl)
                .addGap(28, 28, 28)
                .addComponent(city_lbl)
                .addGap(18, 18, 18)
                .addComponent(country_lbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nb_place_lbl)
                    .addComponent(nb_place_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(submit)
                .addContainerGap(69, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshComboBox(){
        String[] places = journey.getPlacesArray();
        DefaultComboBoxModel cbm = new DefaultComboBoxModel(places);
        nb_place_box.setModel(cbm);
    }
    
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        int booked_place = Integer.parseInt((String) nb_place_box.getSelectedItem());
        int new_number_place = journey.getNumberPlace() - booked_place;
        if(new_number_place <= 0){
            journey.setNumberPlace(new_number_place);
            refreshComboBox();
            currentframe.getContentPane().removeAll();
            DisplayScreen displayer_screen = new DisplayScreen(
                    contentPane, 
                    currentframe
            );
            currentframe.getContentPane().add(displayer_screen);
            currentframe.getContentPane().validate();
        }
        else{
            return;
        }
    }//GEN-LAST:event_submitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel city_lbl;
    private javax.swing.JLabel country_lbl;
    private javax.swing.JComboBox<String> nb_place_box;
    private javax.swing.JLabel nb_place_lbl;
    private javax.swing.JLabel screen_title_lbl;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
