/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agencevoyage.view;

import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;
import agencevoyage.model.Employee;
import agencevoyage.model.Journey;
import agencevoyage.model.JourneyManager;
import agencevoyage.model.User;
import agencevoyage.model.UserManager;

/**
 *
 * @author UTILISATEUR
 */
public class DisplayScreen extends javax.swing.JPanel {
    
    private JPanel contentPane;
    private JFrame currentframe;
    private JourneyManager displayer;
    /**
     * Creates new form DisplayScreen
     */
    public DisplayScreen(JPanel panel, JFrame frame) {
        displayer = JourneyManager.getInstance(); 
        contentPane = panel;
        currentframe = frame;
        initComponents();
        
        delete.setVisible(false);
        modifier.setVisible(false);
        book.setVisible(false);
        
        User curr_user = UserManager.getInstance().getCurrentUser();
        if((curr_user instanceof Employee)){
            add.setVisible(true);
        }else{
            add.setVisible(false);
        }
        
        journey_table.setDefaultEditor(Object.class, null);
        displayer = JourneyManager.getInstance(); 
        refreshList();

        
    }
    
    public JourneyManager getDisplayer(){
        return displayer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        journey_table = new javax.swing.JTable();
        add = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        disconnect = new javax.swing.JButton();
        contact = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        book = new javax.swing.JButton();

        jLabel1.setText("Les voyages disponibles");

        journey_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Pays", "Ville", "Prix"
            }
        ));
        journey_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                journey_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(journey_table);

        add.setText("Ajouter");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        delete.setText("Supprimer");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        disconnect.setText("Deconnexion");
        disconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectActionPerformed(evt);
            }
        });

        contact.setText("Contacter");
        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });

        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        book.setText("Reserver");
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(contact)
                            .addGap(45, 45, 45)
                            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(53, 53, 53)
                            .addComponent(modifier))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(disconnect)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(book, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disconnect)
                    .addComponent(add))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(book)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contact)
                    .addComponent(delete)
                    .addComponent(modifier))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        currentframe.getContentPane().removeAll();
        AddJourneyScreen add_car = new AddJourneyScreen(contentPane, currentframe);
        currentframe.getContentPane().add(add_car);
        currentframe.getContentPane().validate();
    }//GEN-LAST:event_addActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        if(journey_table.getSelectedRow() != -1){
            JourneyManager.getInstance().deleteCar(journey_table.getSelectedRow());
            refreshList();
            delete.setVisible(false);
            contact.setVisible(false);
            
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void journey_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_journey_tableMouseClicked
        User curr_user = UserManager.getInstance().getCurrentUser();
        if(curr_user instanceof Employee){
            delete.setVisible(true);
            modifier.setVisible(true);
        }
        if( journey_table.getSelectedRow() != -1){
            book.setVisible(true);
        }
        LinkedList<Journey> item_list;
        item_list = JourneyManager.getInstance().getJourneyList();
        int selected_index = journey_table.getSelectedRow();
        Journey curr_item = item_list.get(selected_index);
        if(curr_item.getNumberPlace() <= 0){
            book.setVisible(false);
        }
        
        
        
    }//GEN-LAST:event_journey_tableMouseClicked
    
    private void disconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectActionPerformed
        currentframe.getContentPane().removeAll();
        LogginScreen logger = new LogginScreen(contentPane, currentframe);
        currentframe.getContentPane().add(logger);
        currentframe.getContentPane().validate();
    }//GEN-LAST:event_disconnectActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        currentframe.getContentPane().removeAll();
        AgencyContactScreen contact_screen = new AgencyContactScreen(contentPane, currentframe);
        currentframe.getContentPane().add(contact_screen);
        currentframe.getContentPane().validate();
    }//GEN-LAST:event_contactActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        if(journey_table.getSelectedRow() != -1){
            currentframe.getContentPane().removeAll();
            Journey user_item = displayer.getJourneyList().get(journey_table.getSelectedRow());
            ModifyJourneyScreen modify = new ModifyJourneyScreen(contentPane, currentframe, user_item);
            currentframe.getContentPane().add(modify);
            currentframe.getContentPane().validate();
        }
    }//GEN-LAST:event_modifierActionPerformed

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
        currentframe.getContentPane().removeAll();
            Journey user_item = displayer.getJourneyList().get(journey_table.getSelectedRow());
            BookingScreen modify = new BookingScreen(contentPane, currentframe, user_item);
            currentframe.getContentPane().add(modify);
            currentframe.getContentPane().validate();
    }//GEN-LAST:event_bookActionPerformed
    
    public void refreshList(){
        displayer = JourneyManager.getInstance();
        DefaultTableModel model = new DefaultTableModel(
                displayer.getJourneyArray(),
                new Object[] {"Pays","Ville","Prix","Places"}
        );
        journey_table.setModel(model);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton book;
    private javax.swing.JButton contact;
    private javax.swing.JButton delete;
    private javax.swing.JButton disconnect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable journey_table;
    private javax.swing.JButton modifier;
    // End of variables declaration//GEN-END:variables
}
