/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agencevoyage.view;

import javax.swing.JFrame;
import javax.swing.JPanel;
import agencevoyage.model.UserManager;

/**
 *
 * @author UTILISATEUR
 */
public class LogginScreen extends javax.swing.JPanel {
    private JPanel contentPane;
    private JFrame currentframe;
    /**
     * Creates new form LogginScreen
     */
    public LogginScreen(JPanel panel, JFrame frame) {
        currentframe = frame;
        contentPane = panel;
        initComponents();
        log_message.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        screen_name_lbl = new javax.swing.JLabel();
        identifier_lbl = new javax.swing.JLabel();
        password_lbl = new javax.swing.JLabel();
        identifier = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        subscribe = new javax.swing.JButton();
        log_message = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();

        screen_name_lbl.setText("Connexion");

        identifier_lbl.setText("Identifiant");

        password_lbl.setText("Mot de passe");

        identifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identifierActionPerformed(evt);
            }
        });

        submit.setText("Ok");
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        subscribe.setText("Inscription");
        subscribe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subscribeActionPerformed(evt);
            }
        });

        log_message.setForeground(new java.awt.Color(250, 0, 0));
        log_message.setText("Incorrect");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(screen_name_lbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(subscribe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                                .addComponent(submit))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(identifier_lbl)
                                    .addComponent(password_lbl))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(identifier, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(password)))
                            .addComponent(log_message))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(screen_name_lbl)
                .addGap(13, 13, 13)
                .addComponent(log_message)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identifier_lbl)
                    .addComponent(identifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_lbl)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(subscribe))
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void identifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identifierActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        String to_str_password = String.valueOf(password.getPassword());
        if(UserManager.getInstance().logUser(identifier.getText(), to_str_password)){
            currentframe.getContentPane().removeAll();
            DisplayScreen displayer_screen = new DisplayScreen(
                    contentPane, 
                    currentframe
            );
            currentframe.getContentPane().add(displayer_screen);
            currentframe.getContentPane().validate();
        }else{
            log_message.setVisible(true);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_submitMouseClicked

    private void subscribeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subscribeActionPerformed
        currentframe.getContentPane().removeAll();
        SubscriptionScreen subcription = new SubscriptionScreen(
                contentPane,
                currentframe
        );
        currentframe.getContentPane().add(subcription);
        currentframe.getContentPane().validate();
    }//GEN-LAST:event_subscribeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField identifier;
    private javax.swing.JLabel identifier_lbl;
    private javax.swing.JLabel log_message;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel password_lbl;
    private javax.swing.JLabel screen_name_lbl;
    private javax.swing.JButton submit;
    private javax.swing.JButton subscribe;
    // End of variables declaration//GEN-END:variables
}
