/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agencevoyage.view;

import javax.swing.JFrame;
import javax.swing.JPanel;
import agencevoyage.model.Journey;

/**
 *
 * @author UTILISATEUR
 */
public class ModifyJourneyScreen extends javax.swing.JPanel {

    private JPanel contentPane;
    private JFrame currentframe;
    private Journey journey;
    /**
     * Creates new form ModifyCarOffer
     */
    public ModifyJourneyScreen(JPanel panel, JFrame frame, Journey j) {
        contentPane = panel;
        currentframe = frame;
        journey = j;

        initComponents();
        brand.setText(journey.getCity());
        model.setText(journey.getCountry());
        price.setText(String.valueOf(journey.getPrice()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        brand_lbl = new javax.swing.JLabel();
        model_lbl = new javax.swing.JLabel();
        price_lbl = new javax.swing.JLabel();
        screen_title = new javax.swing.JLabel();
        brand = new javax.swing.JTextField();
        model = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        previous = new javax.swing.JButton();

        brand_lbl.setText("Pays");

        model_lbl.setText("Ville");

        price_lbl.setText("Prix");

        screen_title.setText("Modifier une offre");

        brand.setText("land");

        model.setText("city");

        price.setText("price");

        save.setText("Enregistrer");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        previous.setText("Retour");
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(screen_title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(brand_lbl)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(price_lbl)
                                    .addComponent(model_lbl)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(previous)
                                .addGap(2, 2, 2)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(save)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(model, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                .addComponent(brand)
                                .addComponent(price)))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(screen_title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brand_lbl)
                    .addComponent(brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(model_lbl)
                    .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price_lbl)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(previous))
                .addContainerGap(69, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
        currentframe.getContentPane().removeAll();
        DisplayScreen displayer_screen = new DisplayScreen(
                contentPane, 
                currentframe
        );
        currentframe.getContentPane().add(displayer_screen);
        currentframe.getContentPane().validate();
    }//GEN-LAST:event_previousActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        journey.setCity(brand.getText());
        journey.setCountry(model.getText());
        journey.setPrice(Double.parseDouble(price.getText()));
        currentframe.getContentPane().removeAll();
        this.previousActionPerformed(evt);
    }//GEN-LAST:event_saveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brand;
    private javax.swing.JLabel brand_lbl;
    private javax.swing.JTextField model;
    private javax.swing.JLabel model_lbl;
    private javax.swing.JButton previous;
    private javax.swing.JTextField price;
    private javax.swing.JLabel price_lbl;
    private javax.swing.JButton save;
    private javax.swing.JLabel screen_title;
    // End of variables declaration//GEN-END:variables
}
