/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agencevoyage.view;

import javax.swing.JFrame;
import javax.swing.JPanel;
import agencevoyage.model.Customer;
import agencevoyage.model.User;
import agencevoyage.model.UserManager;

/**
 *
 * @author UTILISATEUR
 */
public class SubscriptionScreen extends javax.swing.JPanel {
    
    private JPanel contentPane;
    private JFrame currentframe;
    
    /**
     * Creates new form Subscription
     */
    public SubscriptionScreen(JPanel panel, JFrame frame) {
        currentframe = frame;
        contentPane = panel;
        initComponents();
        already_exists_lbl.setVisible(false);
        missing_info_lbl.setVisible(false);
        incorrect_phone_lbl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        wrong_user_name_lbl = new javax.swing.JLabel();
        identifier_lbl = new javax.swing.JLabel();
        password_lbl = new javax.swing.JLabel();
        inscription_lbl = new javax.swing.JLabel();
        identifier = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        email_lbl = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        phone_nb = new javax.swing.JTextField();
        phone_nb_lbl = new javax.swing.JLabel();
        already_exists_lbl = new javax.swing.JLabel();
        missing_info_lbl = new javax.swing.JLabel();
        incorrect_phone_lbl = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        wrong_user_name_lbl.setText("utilisateur déja existant");

        identifier_lbl.setText("Identifiant");

        password_lbl.setText("Mot de passe");

        inscription_lbl.setText("Inscription");

        identifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identifierActionPerformed(evt);
            }
        });

        submit.setText("Valider");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        email_lbl.setText("Email");

        phone_nb_lbl.setText("Numéro de téléphone");

        already_exists_lbl.setForeground(new java.awt.Color(255, 0, 0));
        already_exists_lbl.setText("Déjà existant");

        missing_info_lbl.setForeground(new java.awt.Color(255, 0, 0));
        missing_info_lbl.setText("Informations manquantes");

        incorrect_phone_lbl.setForeground(new java.awt.Color(255, 0, 0));
        incorrect_phone_lbl.setText("Incorrect");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(inscription_lbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(identifier_lbl)
                            .addComponent(password_lbl)
                            .addComponent(email_lbl)
                            .addComponent(phone_nb_lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phone_nb)
                            .addComponent(identifier)
                            .addComponent(password)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(missing_info_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submit)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(already_exists_lbl)
                    .addComponent(incorrect_phone_lbl))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(inscription_lbl)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identifier_lbl)
                    .addComponent(identifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(already_exists_lbl))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_lbl)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_lbl)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone_nb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone_nb_lbl)
                    .addComponent(incorrect_phone_lbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(missing_info_lbl))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void identifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identifierActionPerformed
        
    }//GEN-LAST:event_identifierActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        UserManager usermanager = UserManager.getInstance();
        if(usermanager.getUserList() != null){
            for(User u : usermanager.getUserList()){
                if(u.getIdentifier().equals(identifier.getText())){
                    already_exists_lbl.setVisible(true);
                    return;
                }
            }
        }
        if(
                identifier.getText().equals("") ||
                password.getText().equals("") ||
                email.getText().equals("") ||
                phone_nb.getText().equals("")
                ){
            missing_info_lbl.setVisible(true);
            return;
        }
        int phone_number = 0;
        try{
            phone_number = Integer.parseInt(phone_nb.getText());
        }catch(NumberFormatException e){
            incorrect_phone_lbl.setVisible(true);
            return;
        }
        usermanager.addUser(new Customer(
                        identifier.getText(),
                        password.getText(),
                        email.getText(),
                        phone_number
                )
        );
        currentframe.getContentPane().removeAll();
        LogginScreen logging_screen = new LogginScreen(
                contentPane, 
                currentframe
        );
        currentframe.getContentPane().add(logging_screen);
        currentframe.getContentPane().validate();
        
    }//GEN-LAST:event_submitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel already_exists_lbl;
    private javax.swing.JTextField email;
    private javax.swing.JLabel email_lbl;
    private javax.swing.JTextField identifier;
    private javax.swing.JLabel identifier_lbl;
    private javax.swing.JLabel incorrect_phone_lbl;
    private javax.swing.JLabel inscription_lbl;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel missing_info_lbl;
    private javax.swing.JTextField password;
    private javax.swing.JLabel password_lbl;
    private javax.swing.JTextField phone_nb;
    private javax.swing.JLabel phone_nb_lbl;
    private javax.swing.JButton submit;
    private javax.swing.JLabel wrong_user_name_lbl;
    // End of variables declaration//GEN-END:variables
}
